### ISSUE TITLE
About How to train multiple years?

### ISSUE THREAD

**Issue by CongTsang** [antoninodimaggio/Irradiance-RNN#4]
Hi, May I ask you a question?
As you specified in the README, I did follow your instructions to train on 2010 year and test on 2011 year, But how could I train multiple years?
Looking Forward.

**Comment by antoninodimaggio** [comment]
I am implementing this right now. I fell into a rabbit hole of refactoring my code. I should have this done within a day or two with updated documentation, so everything is easy to use.

**Comment by antoninodimaggio** [comment]
@CongTsang I implemented the multi year functionality. Refer to the merged request to see the other stuff that I implemented.

**Comment by CongTsang** [comment]
Thanks, bro
